-- Rerunnable seed: obligation_templates — secteur crèches / accueil du jeune enfant (privé collectif)
-- Codes secteur alignés sur src/lib/sectors.ts : creches
-- applies_to : employee | site | organization (les obligations « véhicule » n’existent pas ici)
--
-- Vérifications croisées : décret 2021-1131 (qualifications), Code travail (SST R4224-15, VIP L4624-1, DUERP R4121-1),
-- C.s.p. (PMI L2324-1 / R2324-1), CASF L133-6 (B3), exercices évacuation (Code travail R4227-39, arrêté ERP 25/06/1980).

with seed (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
) as (
  values
    -- --- Employé : diplômes (sans échéance réglementaire ; contrôle à l’embauche) ---
    (
      'creches',
      'CAP AEPE (agent d''accueil)',
      'Certificat d''aptitude professionnelle — Accompagnant éducatif petite enfance. Diplôme sans date d''expiration ; exigences de poste selon décret 2021-1131.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôler copie certifiée conforme ou diplôme original à l''embauche ; archiver dans le dossier personnel. Pas de renouvellement du titre.',
      'Copie du diplôme, relevé de formation si besoin',
      'Employeur / Direction',
      'https://www.legifrance.gouv.fr',
      'Décret n° 2021-1131 du 30 août 2021 (établissements d''accueil du jeune enfant)',
      E'Bonjour,\n\nVérifier le diplôme CAP AEPE de {employee_name} (contrôle à l''embauche ou mise à jour du dossier).\nProcédure : {renewal_process}',
      10,
      'Diplômes et qualifications',
      'Obligation mère côté qualité d''accueil : adapter le diplôme exigé au poste (agent d''accueil).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'DEAP (auxiliaire de puériculture)',
      'Diplôme d''État d''auxiliaire de puériculture. Sans expiration ; vérification à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle du diplôme à l''embauche ; conservation d''une copie conforme.',
      'Copie du diplôme DEAP',
      'Employeur / Direction',
      'https://www.legifrance.gouv.fr',
      'Décret n° 2021-1131 du 30 août 2021',
      E'Bonjour,\n\nVérifier le DEAP de {employee_name}.\n{renewal_process}',
      11,
      'Diplômes et qualifications',
      'Pour les postes d''auxiliaire de puériculture.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'EJE (éducateur de jeunes enfants / direction)',
      'Diplôme d''État d''éducateur de jeunes enfants — éducateurs et directeurs selon cadrage de l''établissement. Sans expiration ; contrôle à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle du diplôme à l''embauche ; archivage sécurisé.',
      'Copie du diplôme EJE',
      'Employeur / Direction',
      'https://www.legifrance.gouv.fr',
      'Décret n° 2021-1131 du 30 août 2021',
      E'Bonjour,\n\nVérifier le diplôme EJE de {employee_name}.\n{renewal_process}',
      12,
      'Diplômes et qualifications',
      'Adapter aux fiches de poste encadrement / éducation.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'IDE puéricultrice ou médecin (référent santé)',
      'Pour la direction médicale ou l''appui santé : diplôme d''infirmier(ère) puéricultrice ou médecin. Diplômes d''État sans échéance ; vérification à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle des inscriptions à l''ordre (si applicable) et du diplôme à l''embauche.',
      'Copie diplôme, attestation d''immatriculation ordre (IDE)',
      'Ordre infirmier / Employeur',
      'https://www.service-public.fr',
      'Code de la santé publique ; Code de déontologie (professions de santé)',
      E'Bonjour,\n\nContrôler les qualifications santé de {employee_name}.\n{renewal_process}',
      13,
      'Diplômes et qualifications',
      'Uniquement pour les postes concernés.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'SST — Sauveteur Secouriste du Travail',
      'Formation aux premiers secours en milieu professionnel. Recyclage MAC SST tous les 24 mois (7 h minimum).',
      24,
      'employee',
      'pdf',
      '{90,60,30,7}'::integer[],
      'Planifier une session MAC SST (7 h min) avant échéance.',
      'Attestation SST à jour',
      'INRS / organismes habilités',
      'https://www.inrs.fr',
      'Code du travail art. R4224-15',
      E'Bonjour,\n\nLe SST de {employee_name} arrive à échéance le {due_date}.\n{renewal_process}',
      20,
      'Formations obligatoires',
      'Souvent retenu à la place du PSC1 en milieu professionnel.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Gestes d''urgence pédiatriques',
      'Formation spécifique petite enfance (recommandation PMI / bonnes pratiques, souvent exigée contractuellement). Périodicité indicative 24 à 36 mois selon organisme.',
      30,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Inscrire le personnel à une session reconnue ; conserver l''attestation.',
      'Attestation de formation',
      'Organisme de formation / PMI',
      'https://www.ameli.fr',
      'Recommandations PMI ; Code du travail (formation)',
      E'Bonjour,\n\nActualiser la formation urgences pédiatriques pour {employee_name} avant le {due_date}.',
      21,
      'Formations obligatoires',
      'Adapter la liste des participants aux postes en contact direct avec les enfants.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Visite médicale d''aptitude (VIP périodique)',
      'Visite d''information et de prévention : périodicité usuelle tous les 5 ans ; fréquence renforcée si la médecine du travail l''exige.',
      60,
      'employee',
      'pdf',
      '{120,90,30}'::integer[],
      'Organiser le rendez-vous avec le service de santé au travail.',
      'Avis d''aptitude / attestation SST si lié',
      'Service de santé au travail',
      'https://www.service-public.fr',
      'Code du travail art. L4624-1 et suivants',
      E'Bonjour,\n\nVisite médicale à programmer pour {employee_name} avant le {due_date}.',
      30,
      'Santé au travail',
      'L''employeur doit assurer le suivi ; conserver les attestations.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Vaccinations obligatoires du personnel (hépatite B, DTP, coqueluche, ROR selon cas)',
      'Conformité au calendrier vaccinal et obligations pour les professionnels en contact avec de jeunes enfants (dont hépatite B). Mettre à jour les justificatifs.',
      12,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Relancer les salariés pour carnet de vaccination à jour et attestations médicales.',
      'Carnet de vaccination, attestations',
      'Médecin / employeur',
      'https://www.santepubliquefrance.fr',
      'Code de la santé publique (obligations vaccinales)',
      E'Bonjour,\n\nMettre à jour les preuves vaccinales pour {employee_name} avant le {due_date}.',
      31,
      'Santé au travail',
      'Vérifier les cas particuliers (ROR pour personnes nées après 1980, etc.).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Extrait de casier judiciaire (bulletin n° 3)',
      'Obligatoire à l''embauche pour toute personne en contact avec des mineurs. Pas de périodicité légale ; bonne pratique de revérification périodique.',
      36,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Demande en ligne ou en mairie ; conserver la réponse dans le dossier confidentiel.',
      'Bulletin n° 3 de moins de 3 mois (à l''embauche)',
      'Ministère de la Justice',
      'https://www.service-public.fr',
      'Code de l''action sociale et des familles art. L133-6',
      E'Bonjour,\n\nActualiser le bulletin B3 pour {employee_name} (contrôle périodique recommandé) avant le {due_date}.',
      40,
      'Conformité accueil mineurs',
      'Donnée sensible : accès restreint et conservation conforme RGPD.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Entretien professionnel (tous les 2 ans)',
      'Entretien sur la rémunération, le développement des compétences et les perspectives professionnelles.',
      24,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Tenir l''entretien et conserver une trace (compte-rendu signé ou attestation).',
      'Compte-rendu d''entretien professionnel',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail art. L6315-1',
      E'Bonjour,\n\nEntretien professionnel à réaliser pour {employee_name} avant le {due_date}.',
      50,
      'Formation et carrière',
      'Distinct du plan de développement des compétences (niveau entreprise).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Information CPF et accès au compte personnel',
      'Le salarié doit pouvoir prendre connaissance de son Compte personnel de formation et des droits acquis.',
      12,
      'employee',
      'pdf',
      '{30}'::integer[],
      'Diffuser l''information annuelle (affichage, note interne, point RH).',
      'Trace d''information (email, signature, affichage)',
      'Employeur / OPCO',
      'https://www.moncompteformation.gouv.fr',
      'Code du travail (CPF)',
      E'Bonjour,\n\nVérifier l''information CPF pour {employee_name} pour l''échéance du {due_date}.',
      51,
      'Formation et carrière',
      'Souvent traité en lot pour tout le personnel ; ici modèle individuel pour traçabilité.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    -- --- Site ---
    (
      'creches',
      'Agrément PMI (Protection maternelle et infantile)',
      'Autorisation d''ouverture délivrée par le service PMI du conseil départemental : capacité, normes, contrôles. Document central de l''établissement.',
      12,
      'site',
      'pdf',
      '{120,90,30}'::integer[],
      'Maintenir le dossier à jour ; préparer les visites PMI et réponses aux prescriptions.',
      'Arrêté d''agrément / courrier PMI, rapports de visite',
      'PMI — Conseil départemental',
      'https://www.service-public.fr',
      'Code de la santé publique art. L2324-1 et R2324-1 et suivants ; décret 2021-1131',
      E'Bonjour,\n\nContrôle / mise à jour de l''agrément PMI du site pour le {due_date}.',
      1,
      'PMI et autorisation d''accueil',
      'Obligation structurante : sans agrément conforme, l''accueil ne peut pas être légal.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Exercices d''évacuation incendie (ERP type R)',
      'Au moins deux exercices par an pour les ERP ; consigner date, heure, effectifs, durée et observations au registre de sécurité.',
      6,
      'site',
      'pdf',
      '{30,14}'::integer[],
      'Programmer deux exercices annuels (adapter si dortoirs / contraintes PMI).',
      'Feuilles d''émargement, compte-rendu dans le registre de sécurité',
      'Commission de sécurité / services d''incendie',
      'https://www.interieur.gouv.fr',
      'Code du travail art. R4227-39 ; arrêté du 25 juin 1980 (ERP)',
      E'Bonjour,\n\nPlanifier ou documenter les exercices d''évacuation du site avant le {due_date}.',
      2,
      'ERP et incendie',
      'Les crèches relèvent en général des ERP de type R.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Visite commission de sécurité (ERP type R)',
      'Visite périodique de la commission de sécurité selon la catégorie d''ERP (souvent 3 ou 5 ans).',
      36,
      'site',
      'pdf',
      '{180,90,30}'::integer[],
      'Suivre les convocations ; réaliser les travaux prescrits et conserver les attestations.',
      'Procès-verbal de visite, le cas échéant prescriptions',
      'Commission de sécurité',
      'https://www.interieur.gouv.fr',
      'Code de la construction et de l''habitation (ERP)',
      E'Bonjour,\n\nAnticiper la visite commission de sécurité du site (échéance {due_date}).',
      3,
      'ERP et incendie',
      'Adapter la périodicité à la catégorie réelle de l''établissement.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Contrôles techniques périodiques ERP (extincteurs, BAES, électricité, SDI, gaz, ascenseur)',
      'Extincteurs, BAES, installation électrique, détection incendie : vérifications annuelles usuelles ; ascenseur semestriel si présent ; gaz si installation.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Faire appel à des professionnels agréés ; archiver les rapports dans le registre de sécurité.',
      'Rapports de vérification, étiquettes à jour',
      'Bureaux de contrôle / techniciens agréés',
      'https://www.service-public.fr',
      'Code du travail ; Code de la construction et de l''habitation',
      E'Bonjour,\n\nContrôles techniques du site à jour pour le {due_date}.',
      4,
      'ERP et incendie',
      'Créer des sous-dossiers si un équipement ne concerne pas le site (pas d''ascenseur, etc.).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Aires de jeux extérieures (norme EN 1176)',
      'Vérification annuelle recommandée / souvent exigée par les assureurs et les autorités.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Faire contrôler les jeux par un professionnel compétent.',
      'Rapport de contrôle, corrections éventuelles',
      'Prestataire qualifié',
      'https://www.inrs.fr',
      'Norme EN 1176 ; obligations générales de sécurité',
      E'Bonjour,\n\nContrôle des aires de jeux du site avant le {due_date}.',
      5,
      'ERP et incendie',
      'Prévenir les chutes et collisions : risque majeur en crèche.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'DUERP (Document unique d''évaluation des risques)',
      'Mise à jour au moins annuelle et à chaque changement significatif (locaux, effectifs, matériel, accident).',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Réviser le DUERP avec la CSE si elle existe ; informer les travailleurs.',
      'DUERP daté et signé',
      'Employeur',
      'https://www.inrs.fr',
      'Code du travail art. R4121-1',
      E'Bonjour,\n\nRévision DUERP du site pour le {due_date}.',
      6,
      'Prévention des risques',
      'Risques typiques : TMS, chutes, biologique, charge mentale.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Registre de sécurité ERP',
      'Tenue du registre : exercices, vérifications, formations incendie. Présentation immédiate en cas de contrôle.',
      12,
      'site',
      'pdf',
      '{30}'::integer[],
      'Compléter après chaque exercice ou intervention.',
      'Registre à jour ou extrait certifié',
      'Commission de sécurité',
      'https://www.interieur.gouv.fr',
      'Arrêté du 25 juin 1980 (ERP)',
      E'Bonjour,\n\nVérifier la mise à jour du registre de sécurité pour le {due_date}.',
      7,
      'ERP et incendie',
      'Document clef en cas d''inspection.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Règlement intérieur / règlement de fonctionnement',
      'Document obligatoire remis aux familles et affiché ; révision périodique (bonne pratique annuelle).',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Faire valider les modifications (conseil, autorité compétente selon statut) et informer les familles.',
      'Règlement signé, preuve d''information aux familles',
      'Direction / PMI',
      'https://www.legifrance.gouv.fr',
      'Code de la santé publique art. R2324-29',
      E'Bonjour,\n\nRévision / diffusion du règlement de fonctionnement pour le {due_date}.',
      8,
      'Qualité et familles',
      'Inclure les modalités d''accueil, santé, sécurité, droits des familles.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Projet d''établissement',
      'Orientations pédagogiques et projet social. Révision recommandée tous les 3 à 5 ans.',
      48,
      'site',
      'pdf',
      '{120,60,30}'::integer[],
      'Réécrire le projet avec l''équipe et les partenaires ; le soumettre aux instances utiles.',
      'Projet adopté, trace en AG ou CA selon structure',
      'Direction',
      'https://www.legifrance.gouv.fr',
      'Code de la santé publique art. R2324-29',
      E'Bonjour,\n\nActualiser le projet d''établissement pour le {due_date}.',
      9,
      'Qualité et familles',
      'Cadre de l''accueil éducatif et de la qualité.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Protocoles sanitaires (PAI, médicaments, maladies contagieuses)',
      'PAI renouvelé annuellement ou à la rentrée par enfant concerné ; protocoles médicaments et éviction en cas d''épidémie.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Mettre à jour les PAI avec les familles et la PMI ; diffuser les protocoles au personnel.',
      'PAI signés, protocoles internes',
      'Direction / PMI',
      'https://www.ameli.fr',
      'Code de la santé publique ; bonnes pratiques PMI',
      E'Bonjour,\n\nRévision des protocoles sanitaires du site pour le {due_date}.',
      10,
      'Qualité et familles',
      'Le PAI est individualisé ; le modèle agrège la preuve de processus à jour.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Affichages obligatoires (urgences, évacuation, règlement, inspection du travail, médecine du travail, convention collective)',
      'Vérification régulière de la présence et de la lisibilité des affiches réglementaires.',
      12,
      'site',
      'pdf',
      '{30}'::integer[],
      'Contrôle trimestriel ou semestriel ; remplacer les affiches dégradées.',
      'Photos à jour ou liste de contrôle signée',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail',
      E'Bonjour,\n\nContrôle des affichages obligatoires du site pour le {due_date}.',
      11,
      'Qualité et familles',
      'Inclure 15, 17, 18, 112, 119 selon consignes nationales.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    -- --- Organisation ---
    (
      'creches',
      'Plan de développement des compétences',
      'Document d''entreprise recensant actions de formation ; mise à jour annuelle usuelle.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Élaborer ou actualiser le plan avec la direction des ressources humaines.',
      'Plan adopté, tableau de bord formation',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail (formation professionnelle)',
      E'Bonjour,\n\nActualiser le plan de développement des compétences pour le {due_date}.',
      60,
      'Employeur et formation',
      'Complète les entretiens professionnels individuels.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Convention CAF / PSU et rapport d''activité',
      'Conventionnement avec la CAF pour le financement de la prestation d''accueil ; rapport d''activité annuel et respect du barème.',
      12,
      'organization',
      'pdf',
      '{90,30}'::integer[],
      'Transmettre les pièces dans les délais ; suivre les indicateurs contractuels.',
      'Convention signée, rapport d''activité, échanges CAF',
      'CAF',
      'https://www.caf.fr',
      'Code de l''action sociale et des familles ; barème CNAF',
      E'Bonjour,\n\nÉchéance convention / rapport CAF pour le {due_date}.',
      61,
      'Financeurs',
      'Central pour la viabilité économique de la structure.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Assurance responsabilité civile professionnelle',
      'Police RC pro adaptée à l''accueil du jeune enfant ; attestation annuelle.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Renouveler avant expiration ; vérifier les garanties (corporel, immatériel).',
      'Attestation d''assurance',
      'Assureur',
      'https://www.service-public.fr',
      'Code des assurances',
      E'Bonjour,\n\nRenouvellement RC pro avant le {due_date}.',
      62,
      'Assurances',
      'Conserver les attestations accessibles en audit.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Registre unique du personnel',
      'Tenue du registre unique (déclarations, embauches, contrats).',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Mettre à jour à chaque mouvement ; export ou copie pour contrôle.',
      'Extrait à jour ou capture DSN / logiciel RH',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail art. L1221-13',
      E'Bonjour,\n\nVérification registre du personnel pour le {due_date}.',
      63,
      'Employeur et formation',
      'Obligation employeur ; souvent centralisée au siège.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Mutuelle et prévoyance (conformité offre obligatoire)',
      'Attestations de mise en place et de couverture des salariés.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Renégocier si besoin ; communiquer les bulletins aux salariés.',
      'Contrat collectif, attestations',
      'Assureur / RH',
      'https://www.service-public.fr',
      'Code de la sécurité sociale',
      E'Bonjour,\n\nRevoir couvertures mutuelle / prévoyance pour le {due_date}.',
      64,
      'Assurances',
      'Adapter aux effectifs et à la convention collective applicable.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'creches',
      'Affichage de la convention collective applicable',
      'Affichage sur chaque site ou information dématérialisée équivalente selon les règles en vigueur.',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Mettre à jour lors d''avenants ou changement d''IDCC.',
      'Affichette, extrait, ou lien intranet traçable',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail',
      E'Bonjour,\n\nVérifier l''affichage convention collective pour le {due_date}.',
      65,
      'Employeur et formation',
      'Synchroniser avec les sites (preuve par site si besoin).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    )
)
insert into public.obligation_templates (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
)
select
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
from seed
on conflict (sector, name, applies_to) do update
set
  description = excluded.description,
  renewal_months = excluded.renewal_months,
  proof_type = excluded.proof_type,
  alert_days = excluded.alert_days,
  renewal_process = excluded.renewal_process,
  required_documents = excluded.required_documents,
  competent_authority = excluded.competent_authority,
  official_url = excluded.official_url,
  legal_reference = excluded.legal_reference,
  alert_message_template = excluded.alert_message_template,
  inspection_order = excluded.inspection_order,
  inspection_section = excluded.inspection_section,
  help_text = excluded.help_text,
  last_verified_at = excluded.last_verified_at,
  verified_by = excluded.verified_by,
  active = excluded.active;
