-- Rerunnable seed: obligation_templates — secteur ambulances / transport sanitaire
-- Codes secteur alignés sur src/lib/sectors.ts : ambulances
-- Les obligations « par véhicule » utilisent applies_to = site (une unité « site » = un véhicule ou une ambulance dans le produit).
--
-- Vérifications croisées : agrément préfectoral et AMS (C.s.p. R6312-1 s.), FCA DEA (arrêté 26 janv. 2014 — 35 h / 5 ans),
-- AFGSU arrêté 2006, conventionnement CPAM.

with seed (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
) as (
  values
    (
      'ambulances',
      'DEA — Diplôme d''État d''ambulancier (et formation initiale)',
      'Diplôme obligatoire pour le titre d''ambulancier ; formation initiale d''environ 801 h (arrêté en vigueur). Diplôme sans date de fin ; contrôle à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Vérifier l''authenticité du diplôme et l''inscription aux listes si requis.',
      'Copie du diplôme DEA',
      'ARS / préfecture',
      'https://www.legifrance.gouv.fr',
      'Arrêté du 26 janvier 2014 modifié (DEA)',
      E'Bonjour,\n\nVérifier le diplôme DEA de {employee_name}.\n{renewal_process}',
      10,
      'Qualifications',
      'À coupler avec la FCA pour le droit à facturer.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'FCA — Formation continue ambulancier (35 h / 5 ans)',
      'Formation continue obligatoire pour conserver le droit de facturer les transports à l''Assurance Maladie.',
      60,
      'employee',
      'pdf',
      '{180,90,30}'::integer[],
      'Suivre 35 heures sur 5 ans auprès d''un organisme habilité ; conserver le certificat dans le dossier d''agrément.',
      'Attestation FCA, relevé d''heures',
      'ARS / organisme de formation',
      'https://www.legifrance.gouv.fr',
      'Arrêté du 26 janvier 2014 modifié',
      E'Bonjour,\n\nÉchéance FCA pour {employee_name} le {due_date}.\n{renewal_process}',
      11,
      'Qualifications',
      'Sans FCA à jour, perte de la capacité économique de facturation.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'AFGSU niveau 2 (ambulanciers DEA)',
      'Obligatoire pour les ambulanciers ; recyclage tous les 4 ans.',
      48,
      'employee',
      'pdf',
      '{180,90,30}'::integer[],
      'Session AFGSU 2 certifiée.',
      'Attestation AFGSU 2',
      'Organismes certifiés',
      'https://solidarites-sante.gouv.fr',
      'Arrêté du 3 mars 2006 modifié',
      E'Bonjour,\n\nRecycler l''AFGSU 2 de {employee_name} avant le {due_date}.',
      12,
      'Urgences',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'AFGSU niveau 1 (auxiliaires / conducteurs VSL)',
      'Pour le personnel non DEA en contact avec les patients transportés. Recyclage 4 ans.',
      48,
      'employee',
      'pdf',
      '{180,90,30}'::integer[],
      'Session AFGSU 1.',
      'Attestation AFGSU 1',
      'Organismes certifiés',
      'https://solidarites-sante.gouv.fr',
      'Arrêté du 3 mars 2006 modifié',
      E'Bonjour,\n\nRecycler l''AFGSU 1 de {employee_name} avant le {due_date}.',
      13,
      'Urgences',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Permis de conduire et aptitude médicale à la conduite',
      'Permis B minimum ; visite médicale pour aptitude à la conduite professionnelle (tous les 5 ans avant 60 ans, puis plus fréquent). Permis C : visite tous les 5 ans.',
      60,
      'employee',
      'pdf',
      '{120,60,30}'::integer[],
      'Passer la visite chez un médecin agréé ; mettre à jour le suivi dans le dossier conducteur.',
      'Permis valide, certificat d''aptitude',
      'Médecin agréé',
      'https://www.service-public.fr',
      'Code de la route ; réglementation transport sanitaire',
      E'Bonjour,\n\nActualiser permis / aptitude de conduite pour {employee_name} avant le {due_date}.',
      20,
      'Conduite et exposition',
      'Adapter aux catégories de permis exigées par le poste.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Visite médicale d''aptitude au poste',
      'Suivi renforcé recommandé : nuit, manutention, contraintes psychologiques.',
      24,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Rendez-vous médecine du travail.',
      'Avis d''aptitude',
      'Service de santé au travail',
      'https://www.service-public.fr',
      'Code du travail art. L4624-1',
      E'Bonjour,\n\nVisite médicale pour {employee_name} avant le {due_date}.',
      21,
      'Santé au travail',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Vaccinations obligatoires (hépatite B, DTP, etc.)',
      'Personnel de santé et assimilé : respect du calendrier vaccinal.',
      12,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Campagne annuelle ; attestations dans le dossier.',
      'Carnet de vaccination',
      'Médecine du travail',
      'https://www.santepubliquefrance.fr',
      'Code de la santé publique art. L3111-4',
      E'Bonjour,\n\nMise à jour vaccinale pour {employee_name} avant le {due_date}.',
      22,
      'Santé au travail',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Extrait de casier judiciaire (transport de personnes vulnérables)',
      'Bulletin n° 3 à l''embauche ; revue périodique recommandée.',
      36,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Demande en ligne.',
      'Bulletin n° 3',
      'Ministère de la Justice',
      'https://www.service-public.fr',
      'Code de la santé publique ; bonnes pratiques employeur',
      E'Bonjour,\n\nActualiser le B3 pour {employee_name} avant le {due_date}.',
      23,
      'Conformité',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Entretien professionnel (tous les 2 ans)',
      'Obligation générale employeur.',
      24,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Tracer l''entretien.',
      'Compte-rendu',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail art. L6315-1',
      E'Bonjour,\n\nEntretien professionnel pour {employee_name} avant le {due_date}.',
      30,
      'Formation et carrière',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    -- --- Site = véhicule ---
    (
      'ambulances',
      'Agrément ARS — autorisation de mise en service du véhicule',
      'Autorisation délivrée par l''ARS pour chaque véhicule de transport sanitaire. À renouveler ou mettre à jour lors d''un changement de véhicule.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Déposer le dossier auprès de l''ARS ; conserver l''arrêté dans le véhicule et au siège.',
      'Arrêté d''agrément véhicule',
      'ARS',
      'https://solidarites-sante.gouv.fr',
      'Code de la santé publique art. R6312-1 et suivants',
      E'Bonjour,\n\nVérifier l''agrément ARS du véhicule (site) pour le {due_date}.',
      1,
      'Véhicule (suivi type site)',
      'Dans Regultrack : créer un « site » par véhicule pour rattacher ces obligations.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Contrôle technique du véhicule',
      'Obligation annuelle pour les véhicules de transport sanitaire de personnes.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Passer le contrôle dans un centre habilité ; traiter les contre-visites.',
      'Rapport de contrôle technique',
      'Organisme agréé',
      'https://www.service-public.fr',
      'Code de la route ; réglementation VTP',
      E'Bonjour,\n\nContrôle technique du véhicule avant le {due_date}.',
      2,
      'Véhicule (suivi type site)',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Équipements médicaux du véhicule (DEA, brancard, oxygène, trousse)',
      'Défibrillateur obligatoire en ambulance ; maintenance selon fabricant ; matériel conforme à l''arrêté ministériel.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Vérifications périodiques ; carnet d''entretien du matériel.',
      'Rapports de maintenance, étiquettes de contrôle',
      'Prestataires agréés',
      'https://www.legifrance.gouv.fr',
      'Code de la santé publique art. R6312-9',
      E'Bonjour,\n\nContrôle du plateau technique du véhicule pour le {due_date}.',
      3,
      'Véhicule (suivi type site)',
      'Oxygène : bouteilles et contrôles périodiques réglementés.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Désinfection et hygiène des véhicules',
      'Protocole après chaque transport ; traçabilité ; désinfection approfondie périodique.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Tenir un registre ou un logiciel de traçabilité ; audits internes.',
      'Registre de désinfection, fiches produits',
      'ARS ; guides d''hygiène professionnels',
      'https://solidarites-sante.gouv.fr',
      'Bonnes pratiques d''hygiène ; exigences ARS',
      E'Bonjour,\n\nRevue du protocole de désinfection du véhicule pour le {due_date}.',
      4,
      'Véhicule (suivi type site)',
      'Les circulaires ARS précisent souvent le niveau d''exigence local.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Registre de bord et traçabilité des transports',
      'Conservation des feuilles de route, prescriptions, kilométrage et incidents.',
      12,
      'site',
      'pdf',
      '{30}'::integer[],
      'Archivage conforme (durées légales).',
      'Extrait de registre ou export logiciel',
      'ARS / CPAM',
      'https://www.ameli.fr',
      'Code de la santé publique',
      E'Bonjour,\n\nAudit de la traçabilité du véhicule pour le {due_date}.',
      5,
      'Véhicule (suivi type site)',
      'Les bons de transport liés aux prescriptions sont essentiels pour les contrôles CPAM.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Entretien mécanique et carnet d''entretien',
      'Respect du carnet constructeur et des préconisations préfectorales.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Centraliser factures et rapports de garage.',
      'Carnet d''entretien à jour',
      'Garage agréé',
      'https://www.service-public.fr',
      'Réglementation transport',
      E'Bonjour,\n\nRevue entretien mécanique du véhicule pour le {due_date}.',
      6,
      'Véhicule (suivi type site)',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Agrément préfectoral d''entreprise de transport sanitaire',
      'Autorisation d''exercer délivrée par la préfecture du siège ; durée 5 ans renouvelable.',
      60,
      'organization',
      'pdf',
      '{180,120,30}'::integer[],
      'Constituer le dossier de renouvellement avant expiration.',
      'Arrêté préfectoral, pièces justificatives',
      'Préfecture',
      'https://www.legifrance.gouv.fr',
      'Code de la santé publique art. R6312-1',
      E'Bonjour,\n\nRenouvellement agrément préfectoral avant le {due_date}.',
      50,
      'Autorisation d''exercer',
      'Sans agrément pas d''activité légale.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Conventionnement Assurance Maladie (CPAM)',
      'Convention nationale indispensable pour facturer les transports remboursables.',
      12,
      'organization',
      'pdf',
      '{90,30}'::integer[],
      'Suivre les avenants et les contrôles CPAM.',
      'Convention signée, échanges CPAM',
      'CPAM',
      'https://www.ameli.fr',
      'Code de la sécurité sociale',
      E'Bonjour,\n\nRevue convention CPAM pour le {due_date}.',
      51,
      'Financeurs',
      'Les contrôles portent souvent sur la prescription et la justification du transport.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Assurance RC professionnelle transport sanitaire',
      'Garanties adaptées au transport de personnes malades.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Renouveler avant échéance.',
      'Attestation RC pro',
      'Assureur',
      'https://www.service-public.fr',
      'Code des assurances',
      E'Bonjour,\n\nRenouvellement RC pro avant le {due_date}.',
      52,
      'Assurances',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Quota de véhicules et déclarations ARS',
      'Le parc est régulé par l''ARS ; toute évolution doit être déclarée.',
      12,
      'organization',
      'pdf',
      '{90,30}'::integer[],
      'Tenir à jour la cartographie des véhicules agréés.',
      'Courriers ARS, tableaux de parc',
      'ARS',
      'https://solidarites-sante.gouv.fr',
      'Code de la santé publique',
      E'Bonjour,\n\nPoint quota / parc véhicules pour le {due_date}.',
      53,
      'Autorisation d''exercer',
      'Les zones de garde conditionnent l''activité.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Participation au service de garde ambulancière',
      'Planning de garde imposé par l''ARS ; preuve de conformité.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Transmettre les plannings dans les délais ; conserver les accusés de réception.',
      'Plannings validés ARS',
      'ARS',
      'https://solidarites-sante.gouv.fr',
      'Réglementation zonale de garde',
      E'Bonjour,\n\nVérification conformité des plannings de garde pour le {due_date}.',
      54,
      'Opérations',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Convention collective transports — affichage et temps de travail conducteurs',
      'Respect des dispositions sociales propres aux conducteurs (amplitudes, repos).',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Audit RH / paie.',
      'Affiches, relevés de temps',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail ; CCN transports',
      E'Bonjour,\n\nAudit temps de travail / affichages pour le {due_date}.',
      55,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Registre unique du personnel',
      'Tenue obligatoire.',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Mise à jour continue.',
      'Extrait logiciel',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail art. L1221-13',
      E'Bonjour,\n\nContrôle registre du personnel pour le {due_date}.',
      56,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Mutuelle et prévoyance',
      'Couvertures complémentaires obligatoires.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Renouveler les contrats collectifs.',
      'Attestations',
      'Assureur',
      'https://www.service-public.fr',
      'Code de la sécurité sociale',
      E'Bonjour,\n\nRevue mutuelle / prévoyance pour le {due_date}.',
      57,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ambulances',
      'Plan de développement des compétences',
      'Document employeur ; articulation avec FCA et sécurité.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Adoption annuelle ou révision.',
      'Plan signé',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail',
      E'Bonjour,\n\nActualiser le plan de développement des compétences pour le {due_date}.',
      58,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    )
)
insert into public.obligation_templates (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
)
select
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
from seed
on conflict (sector, name, applies_to) do update
set
  description = excluded.description,
  renewal_months = excluded.renewal_months,
  proof_type = excluded.proof_type,
  alert_days = excluded.alert_days,
  renewal_process = excluded.renewal_process,
  required_documents = excluded.required_documents,
  competent_authority = excluded.competent_authority,
  official_url = excluded.official_url,
  legal_reference = excluded.legal_reference,
  alert_message_template = excluded.alert_message_template,
  inspection_order = excluded.inspection_order,
  inspection_section = excluded.inspection_section,
  help_text = excluded.help_text,
  last_verified_at = excluded.last_verified_at,
  verified_by = excluded.verified_by,
  active = excluded.active;
