-- Rerunnable seed: obligation_templates — secteur EHPAD / hébergement médicalisé
-- Codes secteur alignés sur src/lib/sectors.ts : ehpad
--
-- Vérifications croisées : HAS évaluation ESSMS (L312-8, cycle 5 ans), AFGSU (arrêté 3 mars 2006),
-- autorisation ARS / CPOM (CASF L313-1 s.), plan bleu (circulaire 2004), CVS (L311-6).

with seed (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
) as (
  values
    (
      'ehpad',
      'Médecin coordinateur (diplôme + formation coordonnateur)',
      'Médecin diplômé ; diplôme universitaire de médecin coordinateur fortement recommandé / souvent exigé. Diplômes sans échéance ; vérification à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôler inscription à l''Ordre et diplômes à l''embauche.',
      'Copies diplômes, attestation DU coordonnateur si applicable',
      'Ordre des médecins',
      'https://www.has-sante.fr',
      'Code de la santé publique ; bonnes pratiques HAS',
      E'Bonjour,\n\nVérifier les qualifications du médecin coordinateur {employee_name}.\n{renewal_process}',
      10,
      'Diplômes et qualifications',
      'Poste clé pour la qualité des soins et la coordination.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Directeur d''établissement (CAFDES ou titre RNCP niveau I équivalent)',
      'Certificat d''aptitude aux fonctions de directeur d''établissement social ou titre reconnu de niveau comparable.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle du diplôme à l''embauche.',
      'Copie CAFDES ou titre RNCP',
      'Employeur / ARS',
      'https://www.legifrance.gouv.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nVérifier le diplôme de direction de {employee_name}.\n{renewal_process}',
      11,
      'Diplômes et qualifications',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'IDE — Infirmier diplômé d''État',
      'Diplôme d''État infirmier ; vérification à l''embauche et immatriculation ordinaire.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôler diplôme et carte ordinaire.',
      'Copie diplôme, attestation ordre',
      'Ordre infirmier',
      'https://www.service-public.fr',
      'Code de la santé publique',
      E'Bonjour,\n\nVérifier le diplôme IDE de {employee_name}.\n{renewal_process}',
      12,
      'Diplômes et qualifications',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'AS — Diplôme d''État d''aide-soignant (DEAS)',
      'Pour les aides-soignants : DEAS à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle du diplôme.',
      'Copie DEAS',
      'Employeur',
      'https://www.service-public.fr',
      'Code de la santé publique',
      E'Bonjour,\n\nVérifier le DEAS de {employee_name}.',
      13,
      'Diplômes et qualifications',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'AES — Accompagnant éducatif et social',
      'Diplôme d''État pour les postes d''accompagnement social et éducatif.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Contrôle du diplôme à l''embauche.',
      'Copie diplôme AES',
      'Employeur',
      'https://www.service-public.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nVérifier le diplôme AES de {employee_name}.',
      14,
      'Diplômes et qualifications',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Psychomotricien, kinésithérapeute, ergothérapeute, psychologue (diplômes d''État)',
      'Pour les professionnels paramédicaux ou psychologues : diplômes réglementés, contrôle à l''embauche.',
      0,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Vérifier inscription à l''ordre ou au tableau lorsque requis.',
      'Copies diplômes, attestations ordre',
      'Ordres professionnels',
      'https://www.service-public.fr',
      'Code de la santé publique',
      E'Bonjour,\n\nVérifier les titres de {employee_name} pour le poste paramédical / psychologue.',
      15,
      'Diplômes et qualifications',
      'Adapter le modèle au poste réel (un seul type par salarié en pratique).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'AFGSU niveau 2 (professionnels de santé)',
      'Attestation de formation aux gestes et soins d''urgence — niveau 2 pour IDE, AS, médecins. Recyclage tous les 4 ans.',
      48,
      'employee',
      'pdf',
      '{180,90,30}'::integer[],
      'Inscrire à une session AFGSU 2 agréée avant expiration.',
      'Attestation AFGSU 2',
      'Organismes certifiés',
      'https://solidarites-sante.gouv.fr',
      'Arrêté du 3 mars 2006 modifié',
      E'Bonjour,\n\nRecycler l''AFGSU 2 de {employee_name} avant le {due_date}.',
      20,
      'Urgences et sécurité',
      'Moins médiatisé que le SST mais indispensable côté soins.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'AFGSU niveau 1 (personnel non soignant en contact avec les résidents)',
      'Formation aux gestes d''urgence adaptée au public accueilli. Recyclage tous les 4 ans.',
      48,
      'employee',
      'pdf',
      '{180,90,30}'::integer[],
      'Planifier le recyclage avec un organisme habilité.',
      'Attestation AFGSU 1',
      'Organismes certifiés',
      'https://solidarites-sante.gouv.fr',
      'Arrêté du 3 mars 2006 modifié',
      E'Bonjour,\n\nRecycler l''AFGSU 1 de {employee_name} avant le {due_date}.',
      21,
      'Urgences et sécurité',
      'Pour agents hôtelières, services généraux en contact résidents, etc.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'SST — personnel non soignant',
      'Recyclage MAC SST tous les 24 mois pour les salariés non couverts par AFGSU au même titre.',
      24,
      'employee',
      'pdf',
      '{90,60,30,7}'::integer[],
      'Session MAC SST 7 h minimum.',
      'Attestation SST',
      'INRS / organismes habilités',
      'https://www.inrs.fr',
      'Code du travail art. R4224-15',
      E'Bonjour,\n\nRecycler le SST de {employee_name} avant le {due_date}.',
      22,
      'Urgences et sécurité',
      'Éviter le doublon avec AFGSU selon le poste.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Visite médicale d''aptitude',
      'Visite initiale et suivi périodique ; renforcement si nuit, manutention, exposition particulière.',
      24,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Organiser avec le service de santé au travail selon la fiche de poste.',
      'Avis d''aptitude',
      'Service de santé au travail',
      'https://www.service-public.fr',
      'Code du travail art. L4624-1',
      E'Bonjour,\n\nVisite médicale pour {employee_name} avant le {due_date}.',
      30,
      'Santé au travail',
      'Les EHPAD ont des risques TMS et biologiques élevés : suivis renforcés fréquents.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Vaccinations obligatoires et recommandations (hépatite B, DTP, grippe, etc.)',
      'Hépatite B obligatoire pour les soignants ; DTP à jour ; grippe saisonnière fortement recommandée (quasi-systématique en pratique).',
      12,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Campagnes annuelles ; traçabilité dans le dossier santé.',
      'Attestations vaccinales',
      'Médecine du travail / ARS',
      'https://www.santepubliquefrance.fr',
      'Code de la santé publique art. L3111-4',
      E'Bonjour,\n\nMettre à jour les vaccinations de {employee_name} pour le {due_date}.',
      31,
      'Santé au travail',
      'Adapter aux circulaires saisonnières.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Formation bientraitance et prévention des maltraitances',
      'Obligation pour tout le personnel en contact avec les résidents ; périodicité souvent 3 à 5 ans selon établissement / CPOM.',
      36,
      'employee',
      'pdf',
      '{120,60,30}'::integer[],
      'Programmer avec un organisme reconnu ; conserver les feuilles de présence.',
      'Attestation de formation',
      'HAS / ARS',
      'https://www.has-sante.fr',
      'Recommandations HAS ; conditions de financement / CPOM',
      E'Bonjour,\n\nRecycler la formation bientraitance pour {employee_name} avant le {due_date}.',
      32,
      'Qualité de la prise en charge',
      'Souvent contrôlée dans le cadre du renouvellement d''autorisation.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Entretien professionnel (tous les 2 ans)',
      'Entretien sur rémunération, compétences et parcours professionnel.',
      24,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Réaliser et tracer l''entretien.',
      'Compte-rendu signé',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail art. L6315-1',
      E'Bonjour,\n\nEntretien professionnel pour {employee_name} avant le {due_date}.',
      40,
      'Formation et carrière',
      'Compléter par la convention collective (FEHAP, FHP, CCNT 66…).',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Habilitation électrique (personnel technique / maintenance)',
      'Selon les tâches sur ou à proximité des installations BT/HT. Recyclage recommandé tous les 3 ans.',
      36,
      'employee',
      'pdf',
      '{90,30}'::integer[],
      'Formation et recyclage chez un organisme certifié.',
      'Attestation d''habilitation',
      'Organisme certificateur',
      'https://www.inrs.fr',
      'Réglementation habilitation électrique',
      E'Bonjour,\n\nRecycler l''habilitation électrique de {employee_name} avant le {due_date}.',
      41,
      'Sécurité des biens et des personnes',
      'Uniquement pour les postes concernés.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Extrait de casier judiciaire (personnel en contact avec personnes vulnérables)',
      'Bulletin n° 3 à l''embauche ; bonne pratique de revérification.',
      36,
      'employee',
      'pdf',
      '{60,30}'::integer[],
      'Demande en ligne ; dossier confidentiel.',
      'Bulletin n° 3',
      'Ministère de la Justice',
      'https://www.service-public.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nActualiser le bulletin B3 pour {employee_name} avant le {due_date}.',
      42,
      'Conformité accueil',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Autorisation d''activité ARS (autorisation de fonctionnement)',
      'Autorisation délivrée par l''ARS ; liée au CPOM ou cadre d''autorisation longue selon situation. Inspections possibles à tout moment.',
      60,
      'site',
      'pdf',
      '{180,120,30}'::integer[],
      'Suivre les demandes de renouvellement et les prescriptions ARS.',
      'Arrêté d''autorisation, courriers ARS',
      'ARS',
      'https://solidarites-sante.gouv.fr',
      'Code de l''action sociale et des familles art. L313-1 et suivants',
      E'Bonjour,\n\nPoint sur l''autorisation ARS du site pour le {due_date}.',
      1,
      'Autorités et gouvernance',
      'Document structurant avec le CPOM.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'CPOM (contrat pluriannuel d''objectifs et de moyens)',
      'Contrat avec ARS et conseil départemental : objectifs, indicateurs, rapport annuel.',
      60,
      'site',
      'pdf',
      '{180,90,30}'::integer[],
      'Préparer le rapport d''activité et les échanges avec les financeurs.',
      'CPOM signé, rapports annuels',
      'ARS / Département',
      'https://solidarites-sante.gouv.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nÉchéance CPOM / reporting pour le site — {due_date}.',
      2,
      'Autorités et gouvernance',
      'La double tutelle ARS + département est centrale en EHPAD.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Évaluation qualité HAS (ESSMS)',
      'Depuis la réforme : évaluation nationale tous les 5 ans pour les ESSMS dont les EHPAD.',
      60,
      'site',
      'pdf',
      '{365,180,90}'::integer[],
      'Préparer le dossier et la visite de l''organisme accrédité.',
      'Rapport HAS, plan d''actions',
      'Haute Autorité de santé',
      'https://www.has-sante.fr',
      'Code de l''action sociale et des familles art. L312-8',
      E'Bonjour,\n\nPréparer / suivre l''évaluation HAS du site pour le {due_date}.',
      3,
      'Qualité de la prise en charge',
      'Remplace progressivement les anciens dispositifs type ANESM.',
      current_date,
      'Seed vérifiée web 2026-04 (HAS)',
      true
    ),
    (
      'ehpad',
      'Plan Bleu (canicule)',
      'Plan obligatoire depuis 2004 : organisation, référent, actions en période de forte chaleur.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Mettre à jour annuellement et tester les procédures.',
      'Plan signé, preuve d''information du personnel',
      'ARS / DGAS',
      'https://solidarites-sante.gouv.fr',
      'Circulaire DGAS/SD2C/2004/310',
      E'Bonjour,\n\nActualiser le Plan Bleu du site pour le {due_date}.',
      4,
      'Continuité et crises',
      'Inclure désignation du référent canicule.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Plan de continuité d''activité (PCA)',
      'Scénarios épidémie, canicule, pénurie de personnel, coupure fournisseurs.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Réviser après chaque exercice ou crise majeure.',
      'PCA daté, comptes rendus d''exercices',
      'Direction / gouvernance',
      'https://www.service-public.fr',
      'Bonnes pratiques ; exigences ARS selon dossiers',
      E'Bonjour,\n\nRévision PCA du site pour le {due_date}.',
      5,
      'Continuité et crises',
      'Renforcé depuis la crise sanitaire.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'DUERP (Document unique d''évaluation des risques)',
      'Mise à jour annuelle minimum et après tout changement significatif. Risques spécifiques : TMS, infections, violence, stress.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Associer la CSE ; communiquer les mesures de prévention.',
      'DUERP signé',
      'Employeur',
      'https://www.inrs.fr',
      'Code du travail art. R4121-1',
      E'Bonjour,\n\nRévision DUERP du site pour le {due_date}.',
      6,
      'Prévention des risques',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Commission de sécurité ERP (type J)',
      'EHPAD = ERP type J ; visite périodique (souvent tous les 3 ans pour catégories 1 à 3).',
      36,
      'site',
      'pdf',
      '{180,90,30}'::integer[],
      'Répondre aux prescriptions ; conserver les PV.',
      'Procès-verbaux de visite',
      'Commission de sécurité',
      'https://www.interieur.gouv.fr',
      'Code de la construction et de l''habitation',
      E'Bonjour,\n\nVisite commission de sécurité — échéance {due_date}.',
      7,
      'ERP et incendie',
      'Adapter à la catégorie d''ERP.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Contrôles techniques ERP (extincteurs, SSI, électricité, gaz, désenfumage, appels malade)',
      'Vérifications annuelles usuelles pour les équipements réglementés ; ascenseur semestriel.',
      12,
      'site',
      'pdf',
      '{90,30}'::integer[],
      'Centraliser les rapports dans le registre de sécurité.',
      'Rapports de contrôle',
      'Organismes agréés',
      'https://www.service-public.fr',
      'Code du travail ; CCH',
      E'Bonjour,\n\nContrôles techniques du site pour le {due_date}.',
      8,
      'ERP et incendie',
      'Inclure maintenance des dispositifs d''appel malade / télévigilance si présents.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Ascenseur — vérification périodique',
      'Contrôle semestriel obligatoire pour les ascenseurs.',
      6,
      'site',
      'pdf',
      '{45,14}'::integer[],
      'Contrat avec un organisme accrédité.',
      'Rapports semestriels',
      'Bureau de contrôle',
      'https://www.service-public.fr',
      'Réglementation des ascenseurs',
      E'Bonjour,\n\nContrôle ascenseur du site pour le {due_date}.',
      9,
      'ERP et incendie',
      'Uniquement si l''établissement est équipé.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Exercices d''évacuation incendie',
      'Au moins deux par an ; adapter aux résidents à mobilité réduite. Consigner au registre.',
      6,
      'site',
      'pdf',
      '{30,14}'::integer[],
      'Alterner scénarios (jour / équipe) selon les possibilités médicales.',
      'Comptes rendus dans le registre de sécurité',
      'SSI / commission de sécurité',
      'https://www.interieur.gouv.fr',
      'Code du travail art. R4227-39',
      E'Bonjour,\n\nPlanifier les exercices d''évacuation avant le {due_date}.',
      10,
      'ERP et incendie',
      'Spécificité majeure EHPAD : évacuation des personnes dépendantes.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Registre de sécurité',
      'Suivi des contrôles, exercices et formations incendie.',
      12,
      'site',
      'pdf',
      '{30}'::integer[],
      'Mise à jour continue.',
      'Registre ou extrait',
      'Commission de sécurité',
      'https://www.interieur.gouv.fr',
      'ERP',
      E'Bonjour,\n\nVérifier le registre de sécurité pour le {due_date}.',
      11,
      'ERP et incendie',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Protocoles de soins, pharmacie, prévention des infections, contention',
      'Circuit du médicament, hygiène des mains, isolement, protocoles de contention encadrés.',
      12,
      'site',
      'pdf',
      '{60,30}'::integer[],
      'Révision annuelle avec la pharmacie et le médecin coordinateur.',
      'Protocoles datés, validations collégiales',
      'ARS / HAS',
      'https://www.has-sante.fr',
      'Code de la santé publique ; bonnes pratiques',
      E'Bonjour,\n\nRévision des protocoles cliniques du site pour le {due_date}.',
      12,
      'Qualité de la prise en charge',
      'La contention est encadrée strictement.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Affichages obligatoires (droits des résidents, règlement, réclamation, urgences, CVS)',
      'Charte des droits, règlement de fonctionnement, médiation, numéros d''urgence, coordonnées du conseil de la vie sociale.',
      12,
      'site',
      'pdf',
      '{30}'::integer[],
      'Contrôle semestriel des panneaux.',
      'Photos ou liste de contrôle',
      'Inspection / ARS',
      'https://www.service-public.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nContrôle des affichages pour le {due_date}.',
      13,
      'Qualité de la prise en charge',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Conseil de la vie sociale (CVS)',
      'Réunion au moins trois fois par an ; comptes rendus archivés.',
      4,
      'site',
      'pdf',
      '{30,14}'::integer[],
      'Planifier l''ordre du jour avec les représentants des résidents et familles.',
      'Convocations, PV signés',
      'Direction',
      'https://www.legifrance.gouv.fr',
      'Code de l''action sociale et des familles art. L311-6 et R311-1',
      E'Bonjour,\n\nTenue du CVS du site — prochaine échéance {due_date}.',
      14,
      'Gouvernance usagers',
      'Obligatoire pour l''hébergement permanent.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Assurance responsabilité civile professionnelle',
      'Police adaptée aux activités sanitaires et médico-sociales.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Renouveler et vérifier les clauses (maîtrise d''ouvrage, sous-traitance).',
      'Attestation d''assurance',
      'Assureur',
      'https://www.service-public.fr',
      'Code des assurances',
      E'Bonjour,\n\nRenouvellement RC pro avant le {due_date}.',
      60,
      'Assurances',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Rapport financier annuel (compte administratif, budget)',
      'Transmission aux autorités (ARS, département) selon conventions.',
      12,
      'organization',
      'pdf',
      '{90,30}'::integer[],
      'Préparer les états financiers certifiés ou validés par la gouvernance.',
      'Compte administratif, budget prévisionnel',
      'ARS / Conseil départemental',
      'https://solidarites-sante.gouv.fr',
      'Code de l''action sociale et des familles',
      E'Bonjour,\n\nClôture et transmission du rapport financier pour le {due_date}.',
      61,
      'Finance et contrôle',
      'Peut déclencher un contrôle de gestion ARS.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Convention avec l''Assurance Maladie (forfait soins, facturation)',
      'Conventionnement pour la facturation des soins ; contrôles CPAM possibles.',
      12,
      'organization',
      'pdf',
      '{90,30}'::integer[],
      'Mettre à jour les annexes et suivre les réclamations CPAM.',
      'Convention, échanges CPAM',
      'CPAM',
      'https://www.ameli.fr',
      'Code de la sécurité sociale',
      E'Bonjour,\n\nRevue convention assurance maladie pour le {due_date}.',
      62,
      'Finance et contrôle',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Registre unique du personnel',
      'Tenue et mise à jour du registre unique.',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Synchroniser avec la paie et les embauches.',
      'Extrait logiciel RH',
      'Inspection du travail',
      'https://www.service-public.fr',
      'Code du travail art. L1221-13',
      E'Bonjour,\n\nContrôle registre du personnel pour le {due_date}.',
      63,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Affichage convention collective et mutuelle / prévoyance',
      'Preuve d''affichage ou d''information dématérialisée ; contrats de couverture complémentaire.',
      12,
      'organization',
      'pdf',
      '{30}'::integer[],
      'Mettre à jour lors des renégociations.',
      'Affiches, attestations mutuelle',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail',
      E'Bonjour,\n\nVérification affichages et couvertures sociales pour le {due_date}.',
      64,
      'Employeur',
      'CCN 51 FEHAP, FHP ou CCNT 66 selon le statut.',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    ),
    (
      'ehpad',
      'Plan de développement des compétences',
      'Document obligatoire côté employeur ; articulation avec les besoins de l''EHPAD.',
      12,
      'organization',
      'pdf',
      '{60,30}'::integer[],
      'Adopter en instance compétente.',
      'Plan signé',
      'Employeur',
      'https://www.service-public.fr',
      'Code du travail',
      E'Bonjour,\n\nActualiser le plan de développement des compétences pour le {due_date}.',
      65,
      'Employeur',
      '',
      current_date,
      'Seed vérifiée web 2026-04',
      true
    )
)
insert into public.obligation_templates (
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
)
select
  sector,
  name,
  description,
  renewal_months,
  applies_to,
  proof_type,
  alert_days,
  renewal_process,
  required_documents,
  competent_authority,
  official_url,
  legal_reference,
  alert_message_template,
  inspection_order,
  inspection_section,
  help_text,
  last_verified_at,
  verified_by,
  active
from seed
on conflict (sector, name, applies_to) do update
set
  description = excluded.description,
  renewal_months = excluded.renewal_months,
  proof_type = excluded.proof_type,
  alert_days = excluded.alert_days,
  renewal_process = excluded.renewal_process,
  required_documents = excluded.required_documents,
  competent_authority = excluded.competent_authority,
  official_url = excluded.official_url,
  legal_reference = excluded.legal_reference,
  alert_message_template = excluded.alert_message_template,
  inspection_order = excluded.inspection_order,
  inspection_section = excluded.inspection_section,
  help_text = excluded.help_text,
  last_verified_at = excluded.last_verified_at,
  verified_by = excluded.verified_by,
  active = excluded.active;
